export default {
  APP_READY: 'APP_READY',
  SHOW_SPINNER: 'SHOW_SPINNER',
  SHOW_NOTICE: 'SHOW_NOTICE',
  HIDE_SPINNER: 'HIDE_SPINNER',
  NEXT_PAGE: 'NEXT_PAGE',
  LAST_PAGE: 'LAST_PAGE',
  SWITCH_PAGE: 'SWITCH_PAGE',
  LOAD_PAGE: 'LOAD_PAGE',
  CREATE_T: 'CREATE_T',
  UPDATE_HISTORY_CONTENT: 'UPDATE_HISTORY_CONTENT',

  SHOW_MAINMENU: 'SHOW_MAINMENU',
  HIDE_MAINMENU: 'HIDE_MAINMENU'
};
