export default {
  SET_GROUP_FORMAT: 'SET_GROUP_FORMAT',
  ADD_GROUP: 'ADD_GROUP',
  ADD_STAGE: 'ADD_STAGE',
  REMOVE_GROUP: 'REMOVE_GROUP',
  MOVE_GROUP_UP: 'MOVE_GROUP_UP',
  MOVE_GROUP_DOWN: 'MOVE_GROUP_DOWN',
  COPY_GROUP: 'COPY_GROUP'
};
