export default {
  ADD_STAGE: 'ADD_STAGE',
  REMOVE_STAGE: 'REMOVE_STAGE',
  TOGGLE_STAGE: 'TOGGLE_STAGE',
  SET_GROUP_FORMAT: 'SET_GROUP_FORMAT',
  ADD_GROUP: 'ADD_GROUP',
  REMOVE_GROUP: 'REMOVE_GROUP',
  MOVE_GROUP_UP: 'MOVE_GROUP_UP',
  MOVE_GROUP_DOWN: 'MOVE_GROUP_DOWN',
  COPY_GROUP: 'COPY_GROUP',
};
