export default {
  ADD_STAGE: 'ADD_STAGE',
  REMOVE_STAGE: 'REMOVE_STAGE',
  TOGGLE_STAGE: 'TOGGLE_STAGE',
  SET_GROUP_FORMAT: 'SET_GROUP_FORMAT',
  ADD_GROUP: 'ADD_GROUP',
  REMOVE_GROUP: 'REMOVE_GROUP',
  MOVE_GROUP_UP: 'MOVE_GROUP_UP',
  MOVE_GROUP_DOWN: 'MOVE_GROUP_DOWN',
  COPY_GROUP: 'COPY_GROUP',
  EDIT_GROUP_INFO: 'EDIT_GROUP_INFO',
  CHANGE_GROUP_PLAYERS: 'CHANGE_GROUP_PLAYERS',
  EDIT_SCOREBOARD: 'EDIT_SCOREBOARD',
  EDIT_MATCHES: 'EDIT_MATCHES',
  EDIT_MATCH: 'EDIT_MATCH',
  EDIT_STAGE_INFO: 'EDIT_STAGE_INFO',
  EDIT_T_INFO: 'EDIT_T_INFO'
};
